### ISSUE TITLE
Is it possible to use with @import?

### ISSUE THREAD

**Issue by bzerangue** [tailwindcss/custom-forms#12]
I have an existing html base where I cannot change the html markup. I am utilizing this by building my styles as components with `@apply`. That is working great, but my tailwind.css file is getting super long, so I was hoping to separating sections of the tailwind.css in their own files and utilizing @import via your instructions in the documentation, <https://tailwindcss.com/docs/using-with-preprocessors/#build-time-imports>. 

Here is a glance of what my tailwind.css file looks like. 

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

/* basic form */
.mpp_formField {
    @apply block;
}
.mpp_formControl input[type=checkbox] {
    @apply form-checkbox text-indigo-600;
}
```

**I get the following error...**

CssSyntaxError: /Users/bz/Dev/mp-portal-skin-tailwind/public/tailwind.css:94:5: `@apply` cannot be used with `.form-checkbox` because `.form-checkbox` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.form-checkbox` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
[0]

**Comment by adamwathan** [comment]
Yeah unfortunately complex classes like `form-checkbox` can't be used with apply, apply can only be used to apply simple utility classes.

The reason for this is that the `form-checkbox` class includes multiple actual rules:

```css
.form-checkbox { /* ... */ }
.form-checkbox:checked { /* ... */ }
.form-checkbox:focus:not(:checked) { /* ... */ }
.form-checkbox:focus { /* ... */ }
```

...and right now Tailwind is not sophisticated enough to know exactly what to do here. Should it only apply the `.form-checkbox` rules, or should it clone your selector and add the pseudo-selectors to the end and apply those rules too?

I'd like to get this working at some point but for now Tailwind explicitly errors any time you try to apply anything that isn't just a simple utility class.

For your current situation you might be better off using the [postcss-extend](https://github.com/travco/postcss-extend) plugin, just add it to your list of PostCSS plugins *after* Tailwind and do something like this:

```css
.mpp_formControl input[type=checkbox] {
    @extend .form-checkbox;
    @apply text-indigo-600;
}
```

**Comment by bzerangue** [comment]
Thank you @adamwathan! That makes sense. I will try the `@extend` approach.

**Comment by billmn** [comment]
@adamwathan I have tried to use the postcss-extend plugin with SCSS, but doesn't work.

![Schermata 2019-05-26 alle 12 31 33](https://user-images.githubusercontent.com/779534/58380518-711ad180-7fb2-11e9-80ef-c56a94e226b3.png)

**webpack.mix.js**
```js
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');

mix
    .sass('resources/sass/app.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [
            tailwindcss('tailwind.config.js'),
            require('postcss-extend')
        ],
    })

    .js('resources/js/app.js', 'public/js')

    .version();
```

**app.scss**
```sass
input[type=checkbox] {
    @extend form-checkbox;

    @apply
        mr-2
        text-pink-700;
}
```

I'm not sure that I have used it correctly ... did I miss something?

I've also tried to use @extend with other buit-in tailwind classes (like <code>hidden</code>) but same error.

Thoughts?

**Comment by adamwathan** [comment]
Needs to be `@extend .form-checkbox`, note the dot at the beginning of the class 👍

**Comment by billmn** [comment]
@adamwathan I've tried with the dot at the beginning of the class, but same result 😥

**Comment by adamwathan** [comment]
Ah the problem is you are using Sass which also has its own `@extend`. Not sure you will be able to get around that without removing Sass.

Try this:

```css
input[type=checkbox] {
    #{"@extend form-checkbox;"}

    @apply
        mr-2
        text-pink-700;
}
```

It might not work but you might be able to get some similar approach working.

**Comment by billmn** [comment]
Ok, I will take a try .. thank you Adam
