### ISSUE TITLE
Overriding not working with 0.2

### ISSUE THREAD

**Issue by somebody32** [tailwindcss/custom-forms#20]
Hi! I'm trying to upgrade to 0.2 version and moving my simple config from:
```js
customForms: theme => ({ focusShadow: theme("boxShadow.none") })
```

to (according to the docs)
```js
customForms: theme => ({
  input: {
    "&:focus": {
      boxShadow: undefined
    }
  }
})
```

and still seeing boxShadow on inputs.

I did a quick console.log driven debugging and found out that my custom options are not even passed to `addInput` function. To do that and not to break custom variants it needs to be wrapped into `default` key, ie:

```js
customForms: theme => ({
  default: {
    input: {
      "&:focus": {
        boxShadow: undefined,
      }
    }
  }
})
```

Is that right and docs are just missing that?

**Comment by adamwathan** [comment]
Yep you need the default key, sorry about that I’ll get the docs fixed today.

**Comment by somebody32** [comment]
Great, thank you!
