### ISSUE TITLE
Checkbox Styling ignored in Safari on Mac

### ISSUE THREAD

**Issue by kerrinhardy** [tailwindcss/custom-forms#24]
On MacOS Mojave Version 10.14.5 (18F132) and Safari Version 12.1.1 (14607.2.6.1.1), the checkboxes do not respond to any styling (colours or sizes).  Radio buttons display correctly as styled.

For example, from Workcation live stream:
![image](https://user-images.githubusercontent.com/4270798/61181054-c0e75200-a65f-11e9-94c2-b121cb4f9d56.png)

And viewing the custom-forms documentation page:
![image](https://user-images.githubusercontent.com/4270798/61181016-3a327500-a65f-11e9-9ef4-44f32af9e48a.png)

**Comment by CvX** [comment]
It works correctly here (on 12.1.2 and 13.0 release 87):

<img src="https://user-images.githubusercontent.com/66961/61181114-c7ef6f80-a621-11e9-8cc1-69bc76efd425.png" alt="Safari 12.1.2" width="500">

<img src="https://user-images.githubusercontent.com/66961/61181116-d0e04100-a621-11e9-9ec4-44f327e4cb2f.png" alt="Safari 13.0 release 87" width="500">

**Comment by kerrinhardy** [comment]
Thanks Jarek

I finally worked out what was causing this.  The Kaspersky Security extension in Safari was affecting just the checkbox styling, for some reason.  Nothing to do with TailwindCSS :)
