### ISSUE TITLE
Not working with create-react-app using Tailwind CLI

### ISSUE THREAD

**Issue by sjwinther** [tailwindcss/custom-forms#33]
Trying to follow guide @ https://tailwindcss-custom-forms.netlify.com/, but for some reason the form components aren't ending up in my CSS file. Can't figure out what's wrong.

Using the CLI version of tailwind (version 1.1.2), since we're on create-react-app -> `tailwind build ./src/tailwind.input.css -c ./src/tailwind.config.js -o ./src/index.css`.

Happy to provide any other information that could be of interest :)

**Comment by GeoffSelby** [comment]
Can you share your tailwind.config.js and tailwind.input.css?

**Comment by sjwinther** [comment]
Wow, I goofed on this one. Forgot to import components via `@tailwind components` – thanks!
