### ISSUE TITLE
Custom checkboxes do not work. 

### ISSUE THREAD

**Issue by quanganh2000** [tailwindcss/custom-forms#38]
Checkboxes with customized colors and sizes do not work. Even on the demo site the color is still the same.

**Comment by quanganh2000** [comment]
This is what I have. Same problem on both Safari 13.0.1 and Chrome 77.0.3865.90
<img width="338" alt="Screen Shot 2019-10-15 at 11 56 50 AM" src="https://user-images.githubusercontent.com/46880580/66848621-681ba400-ef43-11e9-9191-e0c0b0d76af3.png">

**Comment by adamwathan** [comment]
Works for me in those same versions, what OS?

**Comment by tlgreg** [comment]
That doesn't seem to be the custom checkbox actually, isn't that the os default?

**Comment by adamwathan** [comment]
Yeah it is, background image isn't being set there either, nor the height, width, or border radius.

**Comment by quanganh2000** [comment]
Im using Mojave 10.14.6

**Comment by quanganh2000** [comment]
yeah nothing is being customized. The custom radio buttons work however.

**Comment by tlgreg** [comment]
Possibly same issue?
https://github.com/tailwindcss/custom-forms/issues/24

**Comment by quanganh2000** [comment]
Oh yeah you are right. It was the Kaspersky Security extension. Working perfectly now. Thank you very much.

**Comment by LeonardoRick** [comment]
I'm facing this issue on iOS mobile (both chrome and safari). Any Idea about what should be?

**Comment by cocotran** [comment]
You can try disabling your antivirus extension to see if it works.
