### ISSUE TITLE
Display issue for select fields

### ISSUE THREAD

**Issue by zamson** [tailwindcss/custom-forms#41]
I'm having some styling issues with select fields. Using the example from the docs the fields does not get styled as expected. This is using tailwind, no other CSS or resets present. Any ideas?

<img width="515" alt="Screenshot 2019-10-24 at 10 40 56" src="https://user-images.githubusercontent.com/11811478/67468683-37c2bc80-f64b-11e9-9932-913882ed2acf.png">

`<label class="block mt-4">
  <span class="text-gray-700">Requested Limit</span>
  <select class="form-select mt-1 block w-full">
    <option>$1,000</option>
    <option>$5,000</option>
    <option>$10,000</option>
    <option>$25,000</option>
  </select>
</label>`

**Comment by adamwathan** [comment]
Can you share your tailwind config, PostCSS config, and the markup for the form?

**Comment by zamson** [comment]
I'm using the HTML from the docs:

`<label class="block mt-4">
  <span class="text-gray-700">Requested Limit</span>
  <select class="form-select mt-1 block w-full">
    <option>$1,000</option>
    <option>$5,000</option>
    <option>$10,000</option>
    <option>$25,000</option>
  </select>
</label>`

Gatsby SASS (from gatsby-config):

`// SASS
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        postCssPlugins: [require('tailwindcss')('./tailwind.config.js')],
      },
    },`

Tailwind config:

`module.exports = {
    theme: {
      extend: {
        colors: {
          'greenpeace-green': '#66CC00',
        }
      }
    },
    plugins: [
      require('@tailwindcss/custom-forms'),
    ]
  }`

**Comment by adamwathan** [comment]
Make sure you install autoprefixer and add it to your PostCSS config 👍 Styling custom form elements relies on the `appearance: none` property which currently requires vendor prefixes in all browsers, but we don't bake those vendor prefixes into Tailwind because we don't want to force all users to support the same browsers.

```js
    {
      resolve: `gatsby-plugin-sass`,  
      options: {  
        postCssPlugins: [
           require('tailwindcss')('./tailwind.config.js'),
           require('autoprefixer'),
        ],  
      },  
    },
```

**Comment by zamson** [comment]
Thanks – It's working 🥳
