### ISSUE TITLE
Form styles getting purged in production 

### ISSUE THREAD

**Issue by ajitbohra** [tailwindcss/custom-forms#45]
**Versions:**
- tailwindcss 1.1.2
- custom-forms 0.2.1

**Misc:**
- package manager yarn
- laravel-mix for bundling
- Using laravel-mix-purgecss 

**Details:**
Form styles are applied to inputs via `@apply` to WordPress generated fields. Form styles works perfect in dev but gets removed in prod.

**Comment by adamwathan** [comment]
Sounds like a purge configuration problem.

**Comment by ajitbohra** [comment]
@adamwathan 
Using laravel-mix-purgecss with following config

```
if ( mix.inProduction() ) {
	mix.purgeCss( {
		folders: [ 'includes', 'src' ],
	} );
}
```

**Comment by ajitbohra** [comment]
Currently styles are applied via `@apply` technically there is no reference to these styles in html/js hence purgecss is removing them !
