### ISSUE TITLE
Nuxt support

### ISSUE THREAD

**Issue by xdiegom** [tailwindcss/custom-forms#49]
Hi there,

I tried to install this package on a NuxtJS project but I not sure if it is a Nuxt issue with the package. I get this error when I add the plugin on the `tailwind.config.js` file the way the docs says:

![image](https://user-images.githubusercontent.com/11020505/69910497-521e5180-13d2-11ea-901e-6249460aa36b.png)

![image](https://user-images.githubusercontent.com/11020505/69910490-416ddb80-13d2-11ea-84af-e831371860db.png)

To make sure if it was a problem with my computer, I cloned the repository, run it and it works. So that's why I am not quite sure if there is something missing to make it work with a NuxtJS project.

**Comment by tlgreg** [comment]
It's a tailwindcss plugin, not a nuxt plugin.

https://github.com/tailwindcss/custom-forms#install

**Comment by xdiegom** [comment]
@tlgreg Shut 🙀!! You are right, having two configs with same variables confused me hahaha.

Thanks!
