### ISSUE TITLE
Separating configuration per form type

### ISSUE THREAD

**Issue by stefanbauer** [tailwindcss/custom-forms#5]
I already tested it on a real project and it works great so far. What do you think about separating some configuration attributes per form type? In my case, for instance, I set the border to none, because I don't need the borders on the input elements (textfield, textarea etc.). But disabling it also disables the border for the checkboxes which is not what I want.

I could imagine that separating it would make sense. What do you think?

**Comment by adamwathan** [comment]
Yeah I think it should be possible to override an option for just a specific element type, falling back to the global configuration if a specific element override is not provided. How do you think those options should be named?

**Comment by stefanbauer** [comment]
My first question would be how the order should be in general. Should we order it alphabetical? Or better logical? To me, it would make to order it per alphabetical. With that in mind, I would go from generic to more precisely.

At the moment it is (for example)

- horizontalPadding
- verticalPadding

I would do it like

- paddingVertical
- paddingHorizontal

Because then the alphabetical order makes sense. At least with these attributes.

For the other elements I could imagine something like a prefix

- checkbox
- radio
- input
- textarea
- multiselect
- select

which would end in something like

```
inputPaddingHorizontal: ...
inputPaddingVertical: ...
inputLineHeight: ...

selectPaddingHorizontal: ...
selectPaddingVertical: ...
selectLineHeight: ...

...
```

**Comment by adamwathan** [comment]
This is out of date now that everything is customizable as hell, so closing.
