### ISSUE TITLE
Different height for input and select on text-xs

### ISSUE THREAD

**Issue by bzrncev** [tailwindcss/custom-forms#57]
When using text-xs and leading-none on text input and select, their heights are different.

Please check this fiddle - https://jsfiddle.net/us5y8nhv/1

**Comment by adamwathan** [comment]
This is just a CSS limitation, browsers ignore a line-height of less than about ~1.15 on inputs and revert to some weird default number, so it's not actually possible to set `line-height: 1` on an input element and have the browser respect it. You'll have to use a different line-height and adjust the padding accordingly if you want the overall control size to be a specific height.
