### ISSUE TITLE
Custom form styles not picked up with minimal tailwind.config.js

### ISSUE THREAD

**Issue by umphy** [tailwindcss/custom-forms#60]
Hi, I am building custom CSS file with Tailwind (1.2.0), Tailwind custom forms (0.2.1), and latest PostCSS and PurgeCSS.

However, with a minimal ```tailwind.config.js``` the built CSS file does not include any of the custom form styles. Only when I use the full Tailwind config file (```tailwind init --full```), do the custom form styles appear in the built CSS file. Below is my minimal ```tailwind.config.js```:

```
module.exports = {
  theme: {
    extend: {
      colors: {
        mycolor: "#c53030"
      }
    },
    variants: {},
    plugins: [require("@tailwindcss/custom-forms")]
  }
};
```

**Comment by adamwathan** [comment]
Plugins and variants should not be nested under theme, they should be root level keys 👍🏻

**Comment by umphy** [comment]
Can't believe I missed that :/ Not sure how that happened...thanks @adamwathan!

I can confirm once the nesting is fixed, everything works as expected.
