### ISSUE TITLE
How to use values from current config inside `customForms` object?

### ISSUE THREAD

**Issue by marbuser** [tailwindcss/custom-forms#9]
So I've been referencing the official Tailwind documentation, but I cannot for the life of me figure out how this works.

This doesn't seem to work;
```js
customForms: {
  verticalPadding: theme => theme('spacing.1'),
}
```

Neither does this;
```js
customForms: {
  verticalPadding: theme => theme('spacing.')[2],
}
```

Which is how the official documentation says to do it.

Error is always the same with either method;
```
TypeError: value.charCodeAt is not a function
```

Hopefully you can help. :)

**Comment by adamwathan** [comment]
Try this:

```js
customForms: theme => ({
  verticalPadding: theme('spacing.1'),
})
```

**Comment by marbuser** [comment]
@adamwathan Thanks that fixed it!
